name: auto-job

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  auto_job:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Launch auto job
        run: ./scripts/auto-job.sh
